# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df8d7604bbcb2e49c18a1329d8f8f99b10bf58a4193eabbfabc023ace255a7994e1689818ff5c1aa8850bfd2f474a611e13d5d09beebcc8a31b6bab91c192181

test:
  secret_key_base: 126809c9a7c3c5369f24caef0661dbdf54778879ddcfabd6a435e3f3048c49465b5332e4a3cf2b1ada9f3d6a3c2342c843a1116c1714f480a276517a6dd2e826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
